apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-raft-config
  namespace: vault
data:
  raft-storage.hcl: |-

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file="/etc/vault-tls/vault-cert/tls.crt"
      tls_key_file="/etc/vault-tls/vault-cert/tls.key"
{{- if .Values.certificate.ca }}
      tls_client_ca_file="/etc/vault-tls/vault-cert/ca.crt"
{{- end }}
    }

    storage "raft" {
      path = "/vault/data"

      retry_join {
        leader_api_addr = "https://vault-active.vault.svc:8200"
        leader_ca_cert_file = {{ (ternary "/etc/vault-tls/vault-cert/ca.crt" "/etc/vault-tls/vault-cert/tls.crt" .Values.certificate.ca) | quote }}
        leader_tls_servername = "{{ print "vault.apps." .Values.dns.zone }}"
      }

    }