apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/name: vault
  name: vault-external
  namespace: vault
spec:
  gateways:
    - vault
  hosts:
    - '*'
  tls:
    - match:
        - port: 443
          sniHosts:
            - {{ print "vault.apps." .Values.dns.zone | quote }}
      route:
        - destination:
            host: vault-active
            port:
              number: 8200
