apiVersion: v2
name: vault
description: Helm chart wrapper for Vault on OpenShift
type: application
version: 0.1.3
appVersion: 0.13.0
dependencies:
  - name: vault
    version: "0.13.0"
    repository: https://helm.releases.hashicorp.com
